version: "3.7"

services:
    web: &WEB
        image: web
        env_file:
            - local.env
        build:
            context: ./web
            dockerfile: Dockerfile
#        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        command: bash /local_run.sh

        ports:
            - "8000:8000"
        volumes:
            - ./web/src:/app
        restart: on-failure
        depends_on:
            - db

    db:
        image: db
        env_file:
            - local.env
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - pgdata:/var/lib/postgresql/data


    db-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        depends_on:
            - db
        ports:
            - "8080:80"

volumes:
   pgdata:
