# Generated by Django 5.0.2 on 2024-03-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABC_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Url')),
                ('file_short_name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Короткое наименование')),
                ('file_name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='downloads', verbose_name='Содержимое файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Исходные файлы',
                'verbose_name_plural': 'Исходный файл',
            },
        ),
        migrations.CreateModel(
            name='Update_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Url')),
                ('count', models.IntegerField(blank=True, default=None, null=True, verbose_name='Количество записей')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_file', to='num_data.abc_files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Статусы обновлений',
                'verbose_name_plural': 'Статусы обновлений',
            },
        ),
        migrations.CreateModel(
            name='ABC_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(blank=True, default=None, null=True, verbose_name='Код оператора')),
                ('from_range', models.IntegerField(blank=True, default=None, null=True, verbose_name='Начало диапазона')),
                ('to_range', models.IntegerField(blank=True, default=None, null=True, verbose_name='Конец дианазона')),
                ('capacity_range', models.IntegerField(blank=True, default=None, null=True, verbose_name='Номерная емкость')),
                ('operator', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Наименование оператора')),
                ('region', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Регион присутствия')),
                ('inn', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='ИНН')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='num_data.abc_files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Содержимое CSV',
                'verbose_name_plural': 'Содержимое CSV',
                'indexes': [models.Index(fields=['cod', 'from_range', 'to_range'], name='num_data_ab_cod_43339a_idx')],
            },
        ),
    ]
